export const isoCountries = {
  "united states of america": "US",
  andorra: "AD",
  anguilla: "AI",
  argentina: "AR",
  australia: "AU",
  austria: "AT",
  azerbaijan: "AZ",
  bahamas: "BS",
  bahrain: "BH",
  barbados: "BB",
  belgium: "BE",
  bermuda: "BM",
  brazil: "BR",
  bulgaria: "BG",
  canada: "CA",
  chile: "CL",
  china: "CN",
  colombia: "CO",
  "costa rica": "CR",
  croatia: "HR",
  cyprus: "CY",
  "czech republic": "CZ",
  denmark: "DK",
  "dominican republic": "DO",
  ecuador: "EC",
  estonia: "EE",
  "faroe islands": "FO",
  finland: "FI",
  france: "FR",
  georgia: "GE",
  germany: "DE",
  ghana: "GH",
  gibraltar: "GI",
  "great britain": "GB",
  greece: "GR",
  "hong kong": "HK",
  hungary: "HU",
  iceland: "IS",
  india: "IN",
  ireland: "IE",
  israel: "IL",
  italy: "IT",
  jamaica: "JM",
  japan: "JP",
  "korea, republic of": "KR",
  latvia: "LV",
  lebanon: "LB",
  lithuania: "LT",
  luxembourg: "LU",
  malaysia: "MY",
  malta: "MT",
  mexico: "MX",
  monaco: "MC",
  montenegro: "ME",
  morocco: "MA",
  netherlands: "NL",
  "netherlands antilles": "AN",
  "new zealand": "NZ",
  "northern ireland": "ND",
  norway: "NO",
  peru: "PE",
  poland: "PL",
  portugal: "PT",
  romania: "RO",
  "russian federation": "RU",
  saint_lucia: "LC",
  saudi_arabia: "SA",
  serbia: "RS",
  singapore: "SG",
  slovakia: "SK",
  slovenia: "SI",
  "south africa": "ZA",
  spain: "ES",
  sweden: "SE",
  switzerland: "CH",
  taiwan: "TW",
  thailand: "TH",
  "trinidad and tobago": "TT",
  turkey: "TR",
  ukraine: "UA",
  "united arab emirates": "AE",
  uruguay: "UY",
  venezuela: "VE",
};

export const bigCities = {
  SE: {
    stockholm: "Stockholm",
    gothenburg: "Gothenburg",
    malmö: "Malmö",
    uppsala: "Uppsala",
    västerås: "Västerås",
  },
  DE: {
    berlin: "Berlin",
    munich: "Munich",
    hamburg: "Hamburg",
    cologne: "Cologne",
    frankfurt: "Frankfurt",
  },
  NO: {
    oslo: "Oslo",
    bergen: "Bergen",
    stavanger: "Stavanger",
    trondheim: "Trondheim",
    drammen: "Drammen",
  },
  PL: {
    warsaw: "Warsaw",
    kraków: "Kraków",
    łódź: "Łódź",
    wrocław: "Wrocław",
    gdańsk: "Gdańsk",
  },
  FI: {
    helsinki: "Helsinki",
    espoo: "Espoo",
    tampere: "Tampere",
    vantaa: "Vantaa",
    oulu: "Oulu",
  },
  GB: {
    london: "London",
    birmingham: "Birmingham",
    manchester: "Manchester",
    liverpool: "Liverpool",
    leeds: "Leeds",
  },
  ES: {
    madrid: "Madrid",
    barcelona: "Barcelona",
    valencia: "Valencia",
    seville: "Seville",
    zaragoza: "Zaragoza",
  },
};

export const regionsNotCountries = [
  "usa",
  "canada",
  "europe",
  "australia",
  "new zealand",
  "mexico",
];

export const musicGenres = {
  rock: "KnvZfZ7vAeA",
  pop: "KnvZfZ7vAev",
  hiphop: "KnvZfZ7vAv1",
  "hip hop": "KnvZfZ7vAv1",
  "hip-hop": "KnvZfZ7vAv1",
  rnb: "KnvZfZ7vAee",
  "r&b": "KnvZfZ7vAee",
  jazz: "KnvZfZ7vAvE",
  classical: "KnvZfZ7v7nJ",
  country: "KnvZfZ7vAv6",
  electronic: "KnvZfZ7vAvF",
  reggae: "KnvZfZ7vAv1",
  metal: "KnvZfZ7vAvt",
};
